In [7]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
null_vector[4] = 1
print("1. Null Vector with a 1 at the 5th position:")
print(null_vector)



1. Null Vector with a 1 at the 5th position:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
# 2. Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)
print("2. Vector with values ranging from 10 to 49:")
print(vector)

2. Vector with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# 3. Reverse a vector
r_vector = vector[::-1]
print("\n3. Reversed Vector:")
print(reversed_vector)


3. Reversed Vector:
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [3]:
# 4. Create a 3x3 matrix with values ranging from 0 to 8
m = np.arange(9).reshape(3, 3)
print("\n4. 3x3 Matrix:")
print(m)

In [10]:
# 5. Find indices of non-zero elements from [1,2,0,0,4,0]
array = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(array)
print("5. Indices of Non-Zero Elements:")
print(nonzero_indices)

5. Indices of Non-Zero Elements:
(array([0, 1, 4]),)


In [11]:
# 6. Create a 3x3x3 array with random values
r = np.random.rand(3, 3, 3)
print("6. 3x3x3 Array with Random Values:")
print(r)

6. 3x3x3 Array with Random Values:
[[[0.74991303 0.27246103 0.10784742]
  [0.37439056 0.44814811 0.15140985]
  [0.83400406 0.16845853 0.5394026 ]]

 [[0.20460806 0.50195018 0.82968713]
  [0.2227453  0.18296423 0.71968291]
  [0.85103487 0.09494913 0.64500563]]

 [[0.14681432 0.94907069 0.6771356 ]
  [0.54843636 0.94150727 0.21921324]
  [0.77930644 0.73127694 0.03981265]]]


In [16]:
# 7. Create a 10x10 array with random values and find the minimum and maximum values
a_10x10 = np.random.rand(10, 10)
min_v = np.min(a_10x10)
max_v = np.max(a_10x10)
print("7. 10x10 Array with Random Values (Min and Max):")
print("Minimum Value:", min_v)
print("Maximum Value:",max_v)

7. 10x10 Array with Random Values (Min and Max):
Minimum Value: 4.7416245615994335e-05
Maximum Value: 0.9961334913834794


In [ ]:
# 8. Create a 2d array with 1 on the border and 0 inside
a = np.ones((10, 10))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D Array with 1 on the Border and 0 Inside:")
print(border_array)